namespace Anycode.NetCore.ApiTemplate.Models.Internal;

/// <summary>
/// User information used for tracking and analytics - provided by frontend.
/// </summary>
public record UserSourceInfo
{
	/// <summary>
	/// Not actual user ID, but a unique identifier for the user session generated by frontend.
	/// </summary>
	[JsonPropertyName("id")]
	public Guid Id { get; init; }

	/// <summary>
	/// What page the user first visited on the site.
	/// e.g. if page was "https://example.com/ru/games/inzoi", then FirstPage will be "/ru/games/inzoi".
	/// </summary>
	[JsonPropertyName("firstPage")]
	public string FirstPage { get; set; } = "";

	/// <summary>
	/// JS document.referrer
	/// </summary>
	[JsonPropertyName("referrer")]
	public string? Referrer { get; set; }

	[JsonPropertyName("utm_source")]
	public string? UtmSource { get; set; }

	[JsonPropertyName("utm_medium")]
	public string? UtmMedium { get; set; }

	[JsonPropertyName("utm_campaign")]
	public string? UtmCampaign { get; set; }
}